name: nrh

model_type: segmented_regression

segmentation_col: development_type_id

fit_filters:
- nonres_rent_per_sqft > 0

predict_filters:
- non_residential_sqft > 0

min_segment_size: 10

default_config:
    model_expression: np.log1p(nonres_rent_per_sqft) ~ I(year_built < 1940) + I(year_built
        > 2005) + np.log1p(stories) + ave_income + jobs_1500m + year_built + distance_to_coast
        + distance_to_freeway + distance_to_onramp + distance_to_transit
    ytransform: np.exp

models:
    &id001 !!python/long '2':
        fit_parameters:
            Coefficient:
                I(year_built < 1940)[T.True]: 0.7245678704958175
                I(year_built > 2005)[T.True]: 0.09911872046661778
                Intercept: -2.272740970352509
                distance_to_coast: -5.001683998462068e-06
                distance_to_freeway: -5.862619657481423e-06
                jobs_400m: 0.010946281356200387
                nonres_occupancy_3000m: 0.7435930706923758
                np.log1p(stories): 0.40693755159383965
                pecas_price: 0.006948608806773161
                year_built: 0.002208134308593078
            Std. Error:
                I(year_built < 1940)[T.True]: 0.2755760281525553
                I(year_built > 2005)[T.True]: 0.03078605574109795
                Intercept: 1.3839925953279244
                distance_to_coast: 4.253309158412135e-07
                distance_to_freeway: 1.8654953057211255e-06
                jobs_400m: 0.006882533250215561
                nonres_occupancy_3000m: 0.0653089359285537
                np.log1p(stories): 0.040194924654467515
                pecas_price: 0.0016604356559823444
                year_built: 0.0006991526555837183
            T-Score:
                I(year_built < 1940)[T.True]: 2.6292848305902217
                I(year_built > 2005)[T.True]: 3.2195979017311696
                Intercept: -1.6421626662055977
                distance_to_coast: -11.759511975680883
                distance_to_freeway: -3.1426611685925256
                jobs_400m: 1.5904436576252718
                nonres_occupancy_3000m: 11.385778379636248
                np.log1p(stories): 10.124102858558539
                pecas_price: 4.184810643964542
                year_built: 3.1583006814863914
        fit_rsquared: 0.24965886414519878
        fit_rsquared_adj: 0.24593200419890004
        fitted: true
        model_expression: np.log1p(nonres_rent_per_sqft) ~ I(year_built < 1940) +
            I(year_built > 2005) + np.log1p(stories) + jobs_400m + year_built + distance_to_coast
            + distance_to_freeway + pecas_price + nonres_occupancy_3000m
        name: *id001
    &id002 !!python/long '4':
        fit_parameters:
            Coefficient:
                I(year_built < 1940)[T.True]: 0.20739113782551183
                I(year_built > 2005)[T.True]: 0.1357065360618812
                Intercept: -13.002027356840687
                ave_income: 0.00753021367723311
                distance_to_coast: -6.0938517135333045e-06
                jobs_400m: 0.011306389379470257
                nonres_occupancy_3000m: 0.1360238149306887
                np.log1p(stories): 0.09900121995853087
                pecas_price: 0.007409296390877628
                year_built: 0.008010329944229568
            Std. Error:
                I(year_built < 1940)[T.True]: 0.13619902677383963
                I(year_built > 2005)[T.True]: 0.0490934444472507
                Intercept: 1.7749883643724875
                ave_income: 0.003375960081557593
                distance_to_coast: 5.830014589606945e-07
                jobs_400m: 0.007924190133067083
                nonres_occupancy_3000m: 0.09057095819630011
                np.log1p(stories): 0.02263599472121064
                pecas_price: 0.004027051538394552
                year_built: 0.0008932140551756505
            T-Score:
                I(year_built < 1940)[T.True]: 1.5227064593485509
                I(year_built > 2005)[T.True]: 2.764249638415439
                Intercept: -7.325133853166018
                ave_income: 2.230539904298524
                distance_to_coast: -10.452549680401653
                jobs_400m: 1.426819547437346
                nonres_occupancy_3000m: 1.5018480276633022
                np.log1p(stories): 4.373619148522049
                pecas_price: 1.8398811935323434
                year_built: 8.967984659236398
        fit_rsquared: 0.22664981518578908
        fit_rsquared_adj: 0.21987923963780476
        fitted: true
        model_expression: np.log1p(nonres_rent_per_sqft) ~ I(year_built < 1940) +
            I(year_built > 2005) + np.log1p(stories) + ave_income + jobs_400m + year_built
            + distance_to_coast + pecas_price + nonres_occupancy_3000m
        name: *id002
    &id003 !!python/long '5':
        fit_parameters:
            Coefficient:
                I(year_built < 1940)[T.True]: 0.11046802603891163
                I(year_built > 2005)[T.True]: 0.21486725896415476
                Intercept: -4.07346064286084
                ave_income: 0.0488098300059043
                distance_to_coast: -4.982701510827561e-06
                jobs_1500m: 0.038073336837333174
                nonres_occupancy_3000m: 0.4029875504524784
                pecas_price: 0.0056450214373804045
                year_built: 0.003157008992807698
            Std. Error:
                I(year_built < 1940)[T.True]: 0.07115150717027645
                I(year_built > 2005)[T.True]: 0.06410462291684835
                Intercept: 1.4843310353440915
                ave_income: 0.006312637700830616
                distance_to_coast: 5.633456356870185e-07
                jobs_1500m: 0.010048901604647678
                nonres_occupancy_3000m: 0.09299383194435436
                pecas_price: 0.0013877163311047922
                year_built: 0.0007471942897790936
            T-Score:
                I(year_built < 1940)[T.True]: 1.5525746457421448
                I(year_built > 2005)[T.True]: 3.3518215877014716
                Intercept: -2.7443073990004847
                ave_income: 7.732081630390718
                distance_to_coast: -8.844839109742978
                jobs_1500m: 3.7888058153265254
                nonres_occupancy_3000m: 4.333486877856782
                pecas_price: 4.067849682857213
                year_built: 4.225151391000406
        fit_rsquared: 0.16900618756339758
        fit_rsquared_adj: 0.16408177978599547
        fitted: true
        model_expression: np.log1p(nonres_rent_per_sqft) ~ I(year_built < 1940) +
            I(year_built > 2005) + ave_income + jobs_1500m + year_built + distance_to_coast
            + pecas_price + nonres_occupancy_3000m
        name: *id003

fitted: true
